### ISSUE TITLE
See to Action Driven Animation

### ISSUE THREAD

**Issue by ahmedsaheed** [ahmedsaheed/ahmed-Saheed#14]
Try implement action-driven animation [see lukes website](https://lukesmurray.com/blog/using-action-driven-animation)
[Another example here as well](https://tobiasahlin.com/blog/meaningful-motion-w-action-driven-animation/)

On approach would be using an hover effect as shown on lukes website [see implementation here](https://stackoverflow.com/questions/40613997/trying-to-get-iframe-to-appear-on-hover)
[Another Implementation](https://codepen.io/oeproduction/pen/aRroEe)

**Comment by ahmedsaheed** [comment]
Figured Out ! 
Made it more like that on luke's website.
Just like so

```css
<a class="iframe-link" href="https://saheed.codes/uses">Home Page<iframe src="https://saheed.codes/" loading="lazy" style={{width: "100%", height: "600px", border: "0px none"}}></iframe></a>

.iframe-link iframe {
  display: none;
}
.iframe-link:hover iframe {
  -webkit-animation: slow 2s;
       -moz-animation: slow 2s; 
        -ms-animation: slow 2s; 
         -o-animation: slow 2s; 
            animation: slow 2s;
  display: block;
  /* opacity: 1; */

}

@keyframes slow {
  from { opacity: 0; }
  to   { opacity: 1; }
}
```
